steps:
- name: 'heroku/pack'
  args:
    - build
    - --builder
    - heroku/buildpacks
    - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
    - --publish

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
    - --platform=managed
    - --project=$PROJECT_ID
    - --region=us-central1
    - --allow-unauthenticated
    - --memory=256Mi
    - $REPO_NAME
